# CircleCi configuration file

version: 2.1
orbs:
  docker: circleci/docker@2.5.0

jobs:
  build_docker_image:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - docker/check:
          - docker-password: DOCKER_PASSWORD
          - docker-username: DOCKER_USER

workflows:
  build_image:
    jobs:
      - build_docker_image:
          context:
            - context_demo
