# CircleCi configuration file

version: 2.1
orbs:
  docker_orb: circleci/docker@2.5.0

jobs:
  build_docker_image:
    executor: docker_orb/docker
    steps:
      - setup_remote_docker
      - docker_orb/check:
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USER
      - docker_orb/build:
          image: google/apigee-authn-authz:1.5.10
workflows:
  build_image:
    jobs:
      - build_docker_image:
          context:
            - context_demo
