# CircleCi configuration file

version: 2.1

jobs:
  build:
    docker:
      - image: python:3.6.3-jessie

    working_directory: /tmp
    steps:
      - run:
          name: Creating dummy artifacts
          command: |
            echo "My first artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "My second artifact file" > /tmp/artifacts/artifact-2;
      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts

workflows:
  artifact-loading:
    jobs:
      - build