# CircleCi configuration file

version: 2.1
orbs:
  docker_orb: circleci/docker@2.5.0

jobs:
  docker_login_check:
    executor: docker_orb/docker
    steps:
      - setup_remote_docker
      - docker_orb/check:
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USER

workflows:
  docker_login_check:
    jobs:
      - docker_login_check:
          context:
            - context_demo