# CircleCi configuration file

version: 2.1
#
#jobs:
#  run-tests:
#    docker:
#      - image: circleci/node:12
#    steps:
#      - checkout
#      - run:
#          name: Install npm dependencies
#          command: |
#            sudo npm init
#            sudo npm install -g
#      - run:
#          name: Run unit tests
#          command: |
#            npm run test
#  build:
#    docker:
#      - image: circleci/node:12
#    steps:
#      - checkout
#      - run:
#          name: Build the image
#          command: npm run build
#workflows:
#  test-and-build:
#    jobs:
#      - run-tests
#      - build:
#          requires:
#            - run-tests

jobs:
  build:
    docker:
      - image: cimg/python:3
    resource_class: large
    steps:
      - checkout
      - run:
          name: install packages
          command: |
            python -m pip install --upgrade pip
            pip install pandas numpy awscli
  test:
    docker:
      -  image: cimg/python:3
    resource_class: large
    steps:
      - checkout
      - run:
          name: test packages
          command: python -m pytest
      - store_test_results:
          path: ../test_report

workflows:
  test-build:
    jobs:
      - build
      - test:
          requires:
            - build
